import { ChevronLeft, ChevronRight, CircleAlert, LockKeyhole, RefreshCw, RotateCcw, Search, ShieldAlert } from 'lucide-react'

export function BrowserWorkspace() {
  return <section className="browser-workspace">
    <header className="browser-bar"><ChevronLeft size={17}/><ChevronRight size={17}/><RefreshCw size={15}/><label><LockKeyhole size={14}/><input value="http://localhost:8080/dashboard" readOnly /></label><button className="profile-button"><span className="status-dot online"/> Aether Profile</button></header>
    <nav className="browser-tools"><button className="active">DOM</button><button>Screenshot</button><button>Console</button><button>Network</button><span>Site permissions: localhost <i className="status-dot online" /></span></nav>
    <div className="page-preview"><header><strong>Device Dashboard</strong><span className="status-dot online"/> Connected<button>Export report</button></header><aside>{['Overview','System','Interfaces','Logs','Settings'].map((item,index)=><button className={index===0?'active':''} key={item}>{item}</button>)}</aside><main><div className="metric-strip">{[['CPU Load','68.4%'],['RAM Usage','120.7 MB'],['Temperature','42.3 °C'],['UART RX Errors','15']].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong><i /></article>)}</div><div className="device-table"><h3>Recent Events</h3>{[['12:41:21.183','uart','rx_overrun','overrun at 115200 baud'],['12:41:21.991','watchdog','timeout','IWDG reset'],['12:41:20.552','can','bus_off','recovery attempt'],['12:41:18.007','power','wfi_exit','EXTI line 7']].map((row)=><div key={row[0]}>{row.map((cell)=><span key={cell}>{cell}</span>)}</div>)}</div><div className="overflow-annotation"><CircleAlert size={16}/><strong>Overflow</strong><span>Content exceeds container width by 16px</span></div></main></div>
    <div className="browser-bottom"><section><header>DOM <span><Search size={14}/> <RotateCcw size={14}/></span></header><pre>{`<html lang="en">\n  <head>…</head>\n  <body>\n    <div id="root">\n      <div class="app">\n        <aside class="sidebar">…</aside>\n        <main class="content">\n          <section class="events panel">…\n        </main>\n      </div>\n    </div>\n  </body>\n</html>`}</pre></section><section><header><button className="active">Console</button><button>Network</button></header><div className="console-error"><ShieldAlert size={15}/><span>[Layout] Horizontal scroll detected<br/><code>section.events.panel</code> overflows 16px</span></div><div className="console-row">[Info] WebSocket connected to ws://localhost:8080/ws</div><div className="network-table"><span>200</span><code>GET /api/summary</code><small>82 ms</small><span>200</span><code>GET /api/events</code><small>91 ms</small></div></section></div>
  </section>
}
