import { ChevronLeft, ChevronRight, CircleAlert, LockKeyhole, RefreshCw, RotateCcw, Search, ShieldAlert } from 'lucide-react'

export function BrowserWorkspace() {
  return <section className="browser-workspace">
    <header className="browser-bar"><ChevronLeft size={17}/><ChevronRight size={17}/><RefreshCw size={15}/><label><LockKeyhole size={14}/><input value="http://localhost:8080/dashboard" readOnly /></label><button className="profile-button"><span className="status-dot online"/> Aether 独立资料</button></header>
    <nav className="browser-tools"><button className="active">DOM</button><button>截图</button><button>控制台</button><button>网络</button><span>站点权限：localhost <i className="status-dot online" /></span></nav>
    <div className="page-preview"><header><strong>设备仪表盘</strong><span className="status-dot online"/> 已连接<button>导出报告</button></header><aside>{['概览','系统','接口','日志','设置'].map((item,index)=><button className={index===0?'active':''} key={item}>{item}</button>)}</aside><main><div className="metric-strip">{[['CPU 负载','68.4%'],['内存占用','120.7 MB'],['温度','42.3 °C'],['UART RX 错误','15']].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong><i /></article>)}</div><div className="device-table"><h3>最近事件</h3>{[['12:41:21.183','uart','rx_overrun','115200 波特率下发生溢出'],['12:41:21.991','watchdog','timeout','IWDG 复位'],['12:41:20.552','can','bus_off','尝试恢复'],['12:41:18.007','power','wfi_exit','EXTI 线路 7']].map((row)=><div key={row[0]}>{row.map((cell)=><span key={cell}>{cell}</span>)}</div>)}</div><div className="overflow-annotation"><CircleAlert size={16}/><strong>布局溢出</strong><span>内容超出容器宽度 16px</span></div></main></div>
    <div className="browser-bottom"><section><header>DOM <span><Search size={14}/> <RotateCcw size={14}/></span></header><pre>{`<html lang="zh-CN">\n  <head>…</head>\n  <body>\n    <div id="root">\n      <div class="app">\n        <aside class="sidebar">…</aside>\n        <main class="content">\n          <section class="events panel">…\n        </main>\n      </div>\n    </div>\n  </body>\n</html>`}</pre></section><section><header><button className="active">控制台</button><button>网络</button></header><div className="console-error"><ShieldAlert size={15}/><span>[布局] 检测到横向滚动<br/><code>section.events.panel</code> 溢出 16px</span></div><div className="console-row">[信息] WebSocket 已连接至 ws://localhost:8080/ws</div><div className="network-table"><span>200</span><code>GET /api/summary</code><small>82 ms</small><span>200</span><code>GET /api/events</code><small>91 ms</small></div></section></div>
  </section>
}
