# SPDX-License-Identifier: Apache-2.0
# Ed25519 keeps the OTA benchmark cryptographically signed while remaining
# tractable under instruction-level emulation. Hardware equivalence is not
# implied by this simulation-oriented key and algorithm selection.
CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
CONFIG_BOOT_SIGNATURE_KEY_FILE="root-ed25519.pem"
CONFIG_ARM_MPU=n
CONFIG_MPU_STACK_GUARD=n
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
